/* design-library.js: the data behind design.html.
   Generated by scripts/sync-design-library.mjs. Edit `manual` by hand;
   `items` is rebuilt from the Magpie vault on every run. */
window.DESIGN_LIBRARY = {
  "updatedAt": "2026-09-24",
  "systems": [
    {
      "name": "Kelly's lab",
      "site": "kellylucas.dev",
      "status": "live",
      "palette": [
        {
          "name": "page",
          "hex": "#f4f2ec"
        },
        {
          "name": "mint",
          "hex": "#c9e6c9"
        },
        {
          "name": "cream",
          "hex": "#f6f3e8"
        },
        {
          "name": "lilac",
          "hex": "#e3e3ee"
        },
        {
          "name": "ink",
          "hex": "#14201a"
        }
      ],
      "type": "Heliora for everything, 300 to 700.",
      "rules": [
        "Stacked rounded slabs, 28px radius, a dot tag in every corner.",
        "Lilac means unfinished. Say so on the page.",
        "Motion is welcome, never blocks reading, respects reduced motion.",
        "No em dashes. Lowercase-leaning, sentence case."
      ],
      "live": "https://kellylucas.dev",
      "doc": "https://github.com/kellylucas314-cpu/kelly-lucas-dev/blob/main/CLAUDE.md",
      "docLabel": "CLAUDE.md"
    },
    {
      "name": "Pretzel Protocol",
      "site": "pretzel.thetravelprotocol.com",
      "status": "live",
      "palette": [
        {
          "name": "paper",
          "hex": "#faf9f5"
        },
        {
          "name": "rail",
          "hex": "#f3eee4"
        },
        {
          "name": "band",
          "hex": "#e4d7b8"
        },
        {
          "name": "ink",
          "hex": "#103044"
        },
        {
          "name": "signal",
          "hex": "#1a5c4a"
        },
        {
          "name": "cranberry",
          "hex": "#b84a45"
        }
      ],
      "type": "Literata for headings, Hanken Grotesk for everything else.",
      "rules": [
        "Cranberry is the one attention color, and only ever a chip.",
        "Delight budget of five. To add a sixth, remove one.",
        "Nothing under 12px, inputs at 16px, touch targets 44px.",
        "Anything a drawing sits on is the art's own cream."
      ],
      "live": "https://pretzel.thetravelprotocol.com",
      "doc": "https://github.com/kellylucas314-cpu/pretzel-protocol/blob/main/DESIGN-SYSTEM.md",
      "docLabel": "DESIGN-SYSTEM.md"
    },
    {
      "name": "Heliopolis",
      "site": "myheliopolis.com",
      "status": "art direction",
      "palette": [
        {
          "name": "cream",
          "hex": "#FAF9F5"
        },
        {
          "name": "navy",
          "hex": "#103044"
        },
        {
          "name": "lime",
          "hex": "#DAEAAA"
        }
      ],
      "type": "Fine navy outlines, flat fills, little shading.",
      "rules": [
        "One clear idea per image, with generous empty cream around it.",
        "The arch and the sun carry the identity.",
        "No cyan, pink, bright yellow, or any decorative palette.",
        "Illustrations stay secondary to the task, the note, or the document."
      ],
      "live": "https://myheliopolis.com/",
      "doc": "https://github.com/kellylucas314-cpu/heliopolis-art-library/blob/main/ART%20DIRECTION%20-%20ORIGINAL%20HELIOPOLIS.md",
      "docLabel": "Art direction"
    },
    {
      "name": "Agent Commons",
      "site": "the brain room",
      "status": "private",
      "palette": [
        {
          "name": "page",
          "hex": "#f7f7f7"
        },
        {
          "name": "ink",
          "hex": "#1e1e1e"
        },
        {
          "name": "mint",
          "hex": "#258360"
        },
        {
          "name": "slate",
          "hex": "#304a57"
        },
        {
          "name": "violet",
          "hex": "#652085"
        },
        {
          "name": "sky",
          "hex": "#367496"
        },
        {
          "name": "amber",
          "hex": "#8e4605"
        }
      ],
      "type": "GC Protage for display, LeniaSans for body.",
      "rules": [
        "Outline, never elevation. No shadows anywhere.",
        "Amber is reserved for the one thing that needs you.",
        "Rounded corners with the bottom-left squared, on everything you can press.",
        "One seat color per agent. Kelly is graphite because she is the constant."
      ],
      "doc": "https://github.com/kellylucas314-cpu/kelly-lucas-dev/blob/main/docs/agent-commons/DESIGN-SYSTEM.md",
      "docLabel": "DESIGN-SYSTEM.md"
    },
    {
      "name": "HelioFlux",
      "site": "helioflux.co",
      "status": "live",
      "palette": [
        {
          "name": "navy",
          "hex": "#092743"
        },
        {
          "name": "slate",
          "hex": "#2F4562"
        },
        {
          "name": "cyan",
          "hex": "#00A9D6"
        },
        {
          "name": "amber",
          "hex": "#E8A838"
        },
        {
          "name": "coral",
          "hex": "#E85A4F"
        },
        {
          "name": "off-white",
          "hex": "#ECF0FF"
        }
      ],
      "type": "Plus Jakarta Sans for display, DM Sans for body.",
      "rules": [
        "Dark, cinematic, premium. Science that feels important.",
        "Make them feel it before you explain it.",
        "In-vitro results are in-vitro. Say so every time.",
        "No startup clichés, no placeholder images, nothing that looks like a template."
      ],
      "live": "https://helioflux.co",
      "doc": "https://github.com/kellylucas314-cpu/helioflux-website",
      "docLabel": "Source"
    }
  ],
  "libraries": [
    {
      "name": "Heliopolis art library",
      "url": "https://kellylucas.dev/heliopolis/",
      "what": "The original five, the 33 redraws, the style catalog, and art by subject. Cream, navy, lime, one idea per image.",
      "count": "served from the heliopolis-art-library repo"
    },
    {
      "name": "HelioFlux design library",
      "url": "https://github.com/kellylucas314-cpu/helioflux-design-library",
      "what": "Everything collected for the investor site: references, visual concepts, the Dala particle studies, written directions, and the seven-page design guide.",
      "count": "60 references, 24 concepts, 5 studies, 13 ideas",
      "private": true
    },
    {
      "name": "Pretzel illustrations",
      "url": "https://github.com/kellylucas314-cpu/pretzel-protocol/tree/main/assets",
      "what": "My drawings for the family trip atlas: city chapters, each day, each stop, the welcome. Built onto cream by a script that refuses black backgrounds.",
      "count": "source art in assets/, web copies built to public/art/",
      "private": true
    },
    {
      "name": "The audition room",
      "url": "all-fonts.html",
      "what": "Every font that walked into the lab, with the same test sentence. Heliora won.",
      "count": "97 fonts auditioned"
    },
    {
      "name": "The Magpie vault",
      "url": "/brain/gallery.html",
      "what": "Everything clipped, design or not. The desk is a view on the design half of this.",
      "count": "279 clips at last count",
      "private": true
    }
  ],
  "manual": [
    {
      "url": "https://www.isomorphiclabs.com/",
      "title": "Isomorphic Labs",
      "kind": "site",
      "pinned": true,
      "tags": [
        "layout",
        "typography",
        "science"
      ],
      "why": "The north star for this whole site. Stacked slabs, dot tags, huge quiet type. Deep science that never looks like a hospital.",
      "added": "2026-09-24"
    },
    {
      "url": "https://linear.app/",
      "title": "Linear",
      "kind": "site",
      "pinned": true,
      "tags": [
        "clarity",
        "states",
        "product"
      ],
      "why": "Clarity. Hover gives you context. A new project greets you with an empty state that guides you instead of a blank screen.",
      "added": "2026-09-24"
    },
    {
      "url": "https://dub.co/",
      "title": "dub.co",
      "kind": "site",
      "tags": [
        "states",
        "onboarding"
      ],
      "why": "The empty dashboard has an animation, a message, and one clear next step. That is the whole lesson on empty states.",
      "added": "2026-09-24"
    },
    {
      "url": "https://vercel.com/",
      "title": "Vercel",
      "kind": "site",
      "tags": [
        "feedback",
        "states"
      ],
      "why": "Deploy, and the status shows up immediately so you know it worked. Success states matter as much as empty ones.",
      "added": "2026-09-24"
    },
    {
      "url": "https://www.notion.so/",
      "title": "Notion",
      "kind": "site",
      "tags": [
        "flow",
        "onboarding"
      ],
      "why": "Built for flow. New teamspace, add your team, or skip. It never traps you in a step.",
      "added": "2026-09-24"
    },
    {
      "url": "https://godly.website/",
      "title": "Godly",
      "kind": "gallery",
      "tags": [
        "web-design",
        "premium"
      ],
      "why": "Premium web design examples, for when Dribbble starts to feel like a wall of shots.",
      "added": "2026-09-24"
    },
    {
      "url": "https://land-book.com/",
      "title": "Land-book",
      "kind": "gallery",
      "tags": [
        "landing-pages",
        "web-design"
      ],
      "why": "Landing page and startup site gallery. Good for studying section order before writing a line of code.",
      "added": "2026-09-24"
    },
    {
      "url": "https://coolors.co/",
      "title": "Coolors",
      "kind": "tool",
      "tags": [
        "color"
      ],
      "why": "Palette generator. Press space until something feels right, then desaturate it a little.",
      "added": "2026-09-24"
    },
    {
      "url": "https://gsap.com/docs/v3/",
      "title": "GSAP docs",
      "kind": "tool",
      "tags": [
        "motion",
        "animation"
      ],
      "why": "The motion library this site runs on. Reading it one plugin at a time.",
      "added": "2026-09-24"
    },
    {
      "url": "https://21st.dev",
      "kind": "tool"
    },
    {
      "url": "https://youtu.be/ZsP20PN14O0",
      "title": "5 Trendy Animations to Steal for Your Next Web Design",
      "author": "Kole Jain",
      "kind": "video",
      "takeaways": [
        "Five buckets cover almost all site motion: entrance, hover or click, scroll, looped, and mouse. Name which one you are building before you build it.",
        "Subtle and classy beats big and flashy. Big animations slow the site down and overwhelm people, which is the opposite of premium.",
        "Preloaders: keep them short, and move the layer underneath as the loader lifts. A frozen page under a moving loader looks broken.",
        "Highlight on scroll is just a two color gradient, almost stacked, masked by the text and slid along with scroll position. Stagger it across lines.",
        "Loops earn their place only when they are slow and minimal. A marquee you can actually read adds to the design. A fast one is noise.",
        "Mouse effects: the CTA that comes to your cursor is the best use. Keep them rare, and have a fallback because tablet and mobile have no cursor."
      ],
      "added": "2026-09-24"
    },
    {
      "url": "https://youtu.be/ADaQuZS04Rc",
      "title": "Stop Making Pretty UIs. Think Like a Product Designer",
      "author": "Kole Jain",
      "kind": "video",
      "takeaways": [
        "UI design decorates one room. Product design plans the whole house: the flow, the function, the wiring, and how it all connects.",
        "Do not just design the happy path. Empty, loading, success, and error states are the tiny moments that make or break the experience.",
        "Think in screens and sequences, not sections. For every screen ask how the user got here and what they need next.",
        "Chain the small decisions. Notion makes a teamspace, then immediately asks you to add people, with a skip. Three tiny choices, one natural flow.",
        "Consistency builds trust. The primary color in a Mac dialog is always the safe action, so you stop reading and just click.",
        "A design system is a decision you can stick to, not hundreds of components. Same buttons, spacing, and type everywhere, so every new screen feels familiar."
      ],
      "added": "2026-09-24"
    },
    {
      "url": "https://youtu.be/7sUUzOCv47U",
      "title": "Mathematically Perfect Typography for Web Design",
      "author": "Kole Jain",
      "kind": "video",
      "takeaways": [
        "One font is fine and two is plenty. Three is pushing it, four is asking for problems. Never set paragraphs in a display or handwritten font.",
        "At small sizes a thinner weight and a lighter color look the same. Use either to build hierarchy. Body stays at 100%, secondary text sits around 40 to 70%.",
        "Size already gives the heading its attention, so leave it plain. Bold the subheadings so they scan. Do not make the smallest text the faintest too.",
        "Scale type from a 16px base by 1.27, the square root of the golden ratio. Use 1.17, the cube root, for dense screens like dashboards and mobile. Straight 1.62 gets huge too fast.",
        "Fluid sizing: one line of CSS slides between the 320px size and the 1920px size, clamped with min and max. No breakpoints.",
        "Line height: about 150% for paragraphs, 110 to 130% for headings. Smaller text and longer lines want more. Auto falls apart at display sizes."
      ],
      "added": "2026-09-24"
    },
    {
      "url": "https://www.awwwards.com/",
      "kind": "gallery",
      "why": "Best for high-polish website benchmarks. Start here when a build begins from style uncertainty."
    },
    {
      "url": "https://dribbble.com/",
      "kind": "gallery",
      "why": "Quick visual and branding sampling. Search web design, sort by popular, screenshot what stops you."
    },
    {
      "url": "https://refero.design/",
      "kind": "gallery",
      "why": "Task-specific web and iOS patterns from real products. My go-to for how a login, a filter, or an onboarding step actually looks."
    },
    {
      "url": "https://mobbin.com/",
      "kind": "gallery",
      "why": "Real product screens and full user journeys. Mood first, then workflow evidence from here."
    },
    {
      "url": "https://www.happyhues.co/",
      "kind": "tool",
      "why": "Applied palettes: every color shown doing a job on a real page instead of floating in a swatch."
    },
    {
      "url": "https://fonts.google.com/",
      "kind": "tool",
      "why": "Implementable typography, with the loading and readability guidance to go with it."
    },
    {
      "url": "https://www.lapa.ninja/",
      "kind": "gallery",
      "why": "Full-page landing benchmarks. Scroll the whole thing and count the sections."
    },
    {
      "url": "https://onepagelove.com",
      "kind": "gallery",
      "why": "Tighter single-page sites and section references. Good for section sequencing."
    },
    {
      "url": "https://pageflows.com/",
      "kind": "gallery",
      "why": "The sequence layer: how a journey unfolds across screens, not just how one screen looks."
    },
    {
      "url": "https://www.pinterest.com/",
      "kind": "gallery",
      "why": "The broadest, least precise end of the taste workflow. Mood boards, then promote the pins that actually shape something."
    },
    {
      "url": "https://savee.com",
      "kind": "gallery",
      "why": "A cleaner, more taste-driven reference feed for when Pinterest and Dribbble get noisy."
    },
    {
      "url": "https://emilkowal.ski/skill",
      "kind": "tool",
      "why": "Agent skills for motion polish: animation review, timing, spacing, and the physical details AI usually misses."
    },
    {
      "url": "https://stitch.withgoogle.com",
      "title": "Stitch",
      "kind": "tool",
      "why": "Google's AI UI ideation tool. Treat the output as a sketch, not a spec."
    },
    {
      "url": "https://www.behance.net/onboarding/hirerCreative",
      "title": "Behance",
      "kind": "gallery",
      "why": "Portfolio browsing and brand work. Lighter use than Dribbble, better for whole identities."
    },
    {
      "url": "https://fontsinuse.com/",
      "title": "Fonts In Use",
      "kind": "tool",
      "why": "Typography in the wild, indexed by typeface and industry. Proof of what a font feels like in context."
    },
    {
      "url": "https://ciechanow.ski/mechanical-watch/",
      "title": "Bartosz Ciechanowski",
      "kind": "site",
      "why": "Interactive explainers where the page itself does the teaching. The gold standard for learning by playing."
    },
    {
      "url": "https://bruno-simon.com/",
      "title": "Bruno Simon",
      "kind": "site",
      "why": "A portfolio you drive a car through. Proof that a site can be a toy and still land the job."
    },
    {
      "url": "https://igloo.inc",
      "title": "Igloo Inc",
      "kind": "site",
      "why": "Scroll-driven 3D storytelling. Study how the motion carries the narrative."
    },
    {
      "url": "https://motionsites.ai/",
      "title": "Motion Sites",
      "kind": "gallery",
      "why": "A gallery of motion-first websites. Watch how each one moves before reading a word."
    },
    {
      "url": "https://principles.design/",
      "title": "Principles.design",
      "kind": "gallery",
      "why": "An open collection of design principles from real teams. Steal the wording, keep the discipline."
    },
    {
      "url": "https://codingfont.com",
      "title": "Coding Font",
      "kind": "tool",
      "why": "A tournament bracket for monospace fonts. Ridiculous and effective."
    },
    {
      "url": "https://skins.webamp.org/index.html",
      "title": "Webamp skins",
      "kind": "site",
      "why": "A museum of Winamp skins. Nostalgia as a lesson in personality over polish."
    },
    {
      "url": "http://animejs.com/",
      "title": "Anime.js",
      "kind": "tool",
      "why": "A lightweight animation library. Worth knowing next to GSAP.",
      "added": "2026-09-24",
      "tags": [
        "motion",
        "animation"
      ]
    },
    {
      "url": "https://recent.design/",
      "title": "Recent",
      "kind": "gallery",
      "tags": [
        "web-design"
      ],
      "why": "Godly's new home, per Jack Roberts' five shelves. Best of recent design, daily.",
      "added": "2026-09-24"
    },
    {
      "url": "https://noiced.com/",
      "title": "Noiced",
      "kind": "gallery",
      "tags": [
        "web-design"
      ],
      "why": "Daily web design inspiration. From Jack's shelf.",
      "added": "2026-09-24"
    },
    {
      "url": "https://landing.love/",
      "title": "Landing.love",
      "kind": "gallery",
      "tags": [
        "motion",
        "landing-pages"
      ],
      "why": "2,000+ animation-heavy landing pages. Pairs with the pink notebook page.",
      "added": "2026-09-24"
    },
    {
      "url": "https://minimal.gallery/",
      "title": "Minimal Gallery",
      "kind": "gallery",
      "tags": [
        "web-design",
        "minimal"
      ],
      "why": "Hand-picked minimal web design. For when the slab layout needs a diet.",
      "added": "2026-09-24"
    },
    {
      "url": "https://siteinspire.com/",
      "title": "Siteinspire",
      "kind": "gallery",
      "tags": [
        "web-design"
      ],
      "why": "Old-school, still one of the cleanest galleries.",
      "added": "2026-09-24"
    },
    {
      "url": "https://app.notion.com/p/The-Design-Loop-Free-Guide-3b8e8d6bd13781ff8bf2fc06fd5d0aac",
      "title": "The Design Loop",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "method"
      ],
      "why": "Interview, preflight, teardown, loop. Name a specific bar, write mechanisms not adjectives, then let three fresh critics judge the render until all three pass. Installed as /design-loop in this repo.",
      "added": "2026-09-24"
    },
    {
      "url": "https://app.notion.com/p/The-Brand-Asset-Machine-3b3e8d6bd13781909d92c4d0cafc7c77",
      "title": "The Brand Asset Machine",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "brand"
      ],
      "why": "A skill that interviews you, fixes a palette, then generates a brand's logo, photography, one motion loop and a texture pack, all inside that palette. Three rules: one product build everywhere, no text in photos, approve the extras.",
      "added": "2026-09-24"
    },
    {
      "url": "https://app.notion.com/p/5-Questions-to-Answer-Before-You-Build-Any-Website-339e8d6bd1378133800bd681d1d24dfe",
      "title": "5 Questions to Answer Before You Build Any Website",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "method"
      ],
      "why": "Who is the visitor, what is the one action, which objections need a section, what is the vibe in one word, and do brand assets exist yet. Answer these before the next HelioFlux or Heliopolis page.",
      "added": "2026-09-24"
    },
    {
      "url": "https://app.notion.com/p/Claude-Fable-5-Website-Design-Prompts-3-Levels-37ee8d6bd1378142b27be3a1480dd0d5",
      "title": "Website Design Prompts, 3 Levels",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "prompts"
      ],
      "why": "Level one describes a site in a line, level two recreates a reference, level three extracts a site's design DNA and rebuilds something original. Level three is the one that matches how this desk works.",
      "added": "2026-09-24"
    },
    {
      "url": "https://app.notion.com/p/The-AI-Native-Client-CMS-Free-Build-Blueprint-374e8d6bd13781559214ffd5ac6041f6",
      "title": "The AI-Native Client CMS Build Blueprint",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "cms"
      ],
      "why": "Ingest a site, freeze the design as a template, expose only content slots, and run every change through a deterministic validator so a client cannot break the layout. Filed for the day the lab needs an editor.",
      "added": "2026-09-24"
    },
    {
      "url": "https://easywebsitebuilder.tech/",
      "title": "Easy Website Builder",
      "kind": "tool",
      "tags": [
        "jack-roberts"
      ],
      "why": "Jack's website builder. Saved to try, not yet opened.",
      "added": "2026-09-24"
    },
    {
      "url": "https://app.notion.com/p/GPT-6-Astra-Is-Here-5-Things-You-NEED-to-Do-With-It-3d2e8d6bd137819f99b2f35862af517b",
      "title": "Five real jobs for a new model",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "method"
      ],
      "why": "Five prompts with a way to check each: find the bottleneck, a one-screen business dashboard, build with the design loop then test like a first-time customer, a filmable UI system from one reference, and a money-leak audit with receipts.",
      "added": "2026-09-24"
    },
    {
      "url": "https://www.youtube.com/watch?v=2ZwO6LhC0SU",
      "kind": "video",
      "title": "Website design in three levels, with Jack Roberts",
      "author": "AI Automations with Jack",
      "added": "2026-09-24",
      "takeaways": [
        "Level one: describe the site in plain words and let the model one-shot it. Fast, and it looks like everyone else's.",
        "Level two: hand over a reference you love and ask for a recreation. Hard mode, and it copies more than it should.",
        "Level three: extract the reference's design DNA, typography, colour, spacing, layout, ratios, then rebuild something original from that blueprint. This is the one that matches the desk.",
        "Open on max effort for the first build, then drop to medium for everything after. Design judgment is where the effort dial matters.",
        "Awwwards is the place he finds references. Higgsfield or Kie.ai when the hero needs a video."
      ]
    },
    {
      "url": "https://myheliopolis.com/meetings/2026-09-17/#home",
      "title": "Heliopolis meeting room",
      "kind": "site",
      "tags": [
        "mine",
        "heliopolis"
      ],
      "why": "The meeting page I built for 2026-09-17. Learned a ton making it. Kept here to measure the next one against.",
      "added": "2026-09-24"
    },
    {
      "url": "https://pretzel.thetravelprotocol.com",
      "title": "Pretzel Protocol",
      "kind": "site",
      "tags": [
        "mine",
        "trip-atlas"
      ],
      "why": "The family trip atlas. Cream, navy, one attention colour, a delight budget of five. Mine, and still teaching me.",
      "added": "2026-09-24"
    },
    {
      "url": "https://ui.aceternity.com",
      "title": "Aceternity UI",
      "kind": "tool",
      "tags": [
        "components",
        "motion"
      ],
      "why": "Animated heroes, spotlight cards, parallax grids. Jack's UI sniping arsenal: snipe it, then make it obey the system.",
      "added": "2026-09-24"
    },
    {
      "url": "https://reactbits.dev",
      "title": "ReactBits",
      "kind": "tool",
      "tags": [
        "components",
        "motion"
      ],
      "why": "Unique animated micro-components nobody recognises from a template. Same rule: restyle to the tokens after sniping.",
      "added": "2026-09-24"
    },
    {
      "url": "https://www.relume.io",
      "title": "Relume",
      "kind": "tool",
      "tags": [
        "wireframes",
        "ai-design"
      ],
      "why": "AI sitemaps and wireframes. Only useful after the five questions are answered, which is the whole point of Jack's guide.",
      "added": "2026-09-24"
    },
    {
      "url": "https://higgsfield.ai",
      "title": "Higgsfield",
      "kind": "tool",
      "tags": [
        "ai-video",
        "brand-assets"
      ],
      "why": "AI image and video. The engine behind the Brand Asset Machine, and where the Magpie Collector already lives.",
      "added": "2026-09-24"
    },
    {
      "url": "https://kie.ai",
      "title": "Kie.ai",
      "kind": "tool",
      "tags": [
        "ai-video",
        "ai-images"
      ],
      "why": "AI images and video by API. The other generator Jack plugs in for hero videos.",
      "added": "2026-09-24"
    }
  ],
  "items": [
    {
      "id": "isomorphiclabs.com",
      "domain": "isomorphiclabs.com",
      "kind": "site",
      "tags": [
        "layout",
        "typography",
        "science"
      ],
      "url": "https://www.isomorphiclabs.com/",
      "title": "Isomorphic Labs",
      "pinned": true,
      "why": "The north star for this whole site. Stacked slabs, dot tags, huge quiet type. Deep science that never looks like a hospital.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "linear.app",
      "domain": "linear.app",
      "kind": "site",
      "tags": [
        "clarity",
        "states",
        "product"
      ],
      "url": "https://linear.app/",
      "title": "Linear",
      "pinned": true,
      "why": "Clarity. Hover gives you context. A new project greets you with an empty state that guides you instead of a blank screen.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "dub.co",
      "domain": "dub.co",
      "kind": "site",
      "tags": [
        "states",
        "onboarding"
      ],
      "url": "https://dub.co/",
      "title": "dub.co",
      "why": "The empty dashboard has an animation, a message, and one clear next step. That is the whole lesson on empty states.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "vercel.com",
      "domain": "vercel.com",
      "kind": "site",
      "tags": [
        "feedback",
        "states"
      ],
      "url": "https://vercel.com/",
      "title": "Vercel",
      "why": "Deploy, and the status shows up immediately so you know it worked. Success states matter as much as empty ones.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "notion.so",
      "domain": "notion.so",
      "kind": "site",
      "tags": [
        "flow",
        "onboarding"
      ],
      "url": "https://www.notion.so/",
      "title": "Notion",
      "why": "Built for flow. New teamspace, add your team, or skip. It never traps you in a step.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "godly.website",
      "domain": "godly.website",
      "kind": "gallery",
      "tags": [
        "web-design",
        "premium"
      ],
      "url": "https://godly.website/",
      "title": "Godly",
      "why": "Premium web design examples, for when Dribbble starts to feel like a wall of shots.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "land-book.com",
      "domain": "land-book.com",
      "kind": "gallery",
      "tags": [
        "landing-pages",
        "web-design"
      ],
      "url": "https://land-book.com/",
      "title": "Land-book",
      "why": "Landing page and startup site gallery. Good for studying section order before writing a line of code.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "coolors.co",
      "domain": "coolors.co",
      "kind": "tool",
      "tags": [
        "color"
      ],
      "url": "https://coolors.co/",
      "title": "Coolors",
      "why": "Palette generator. Press space until something feels right, then desaturate it a little.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "gsap.com/docs/v3",
      "domain": "gsap.com",
      "kind": "tool",
      "tags": [
        "motion",
        "animation"
      ],
      "url": "https://gsap.com/docs/v3/",
      "title": "GSAP docs",
      "why": "The motion library this site runs on. Reading it one plugin at a time.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "youtube:zsp20pn14o0",
      "domain": "youtu.be",
      "kind": "video",
      "tags": [],
      "url": "https://youtu.be/ZsP20PN14O0",
      "title": "5 Trendy Animations to Steal for Your Next Web Design",
      "author": "Kole Jain",
      "takeaways": [
        "Five buckets cover almost all site motion: entrance, hover or click, scroll, looped, and mouse. Name which one you are building before you build it.",
        "Subtle and classy beats big and flashy. Big animations slow the site down and overwhelm people, which is the opposite of premium.",
        "Preloaders: keep them short, and move the layer underneath as the loader lifts. A frozen page under a moving loader looks broken.",
        "Highlight on scroll is just a two color gradient, almost stacked, masked by the text and slid along with scroll position. Stagger it across lines.",
        "Loops earn their place only when they are slow and minimal. A marquee you can actually read adds to the design. A fast one is noise.",
        "Mouse effects: the CTA that comes to your cursor is the best use. Keep them rare, and have a fallback because tablet and mobile have no cursor."
      ],
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "youtube:adaquzs04rc",
      "domain": "youtu.be",
      "kind": "video",
      "tags": [],
      "url": "https://youtu.be/ADaQuZS04Rc",
      "title": "Stop Making Pretty UIs. Think Like a Product Designer",
      "author": "Kole Jain",
      "takeaways": [
        "UI design decorates one room. Product design plans the whole house: the flow, the function, the wiring, and how it all connects.",
        "Do not just design the happy path. Empty, loading, success, and error states are the tiny moments that make or break the experience.",
        "Think in screens and sequences, not sections. For every screen ask how the user got here and what they need next.",
        "Chain the small decisions. Notion makes a teamspace, then immediately asks you to add people, with a skip. Three tiny choices, one natural flow.",
        "Consistency builds trust. The primary color in a Mac dialog is always the safe action, so you stop reading and just click.",
        "A design system is a decision you can stick to, not hundreds of components. Same buttons, spacing, and type everywhere, so every new screen feels familiar."
      ],
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "youtube:7suuzocv47u",
      "domain": "youtu.be",
      "kind": "video",
      "tags": [],
      "url": "https://youtu.be/7sUUzOCv47U",
      "title": "Mathematically Perfect Typography for Web Design",
      "author": "Kole Jain",
      "takeaways": [
        "One font is fine and two is plenty. Three is pushing it, four is asking for problems. Never set paragraphs in a display or handwritten font.",
        "At small sizes a thinner weight and a lighter color look the same. Use either to build hierarchy. Body stays at 100%, secondary text sits around 40 to 70%.",
        "Size already gives the heading its attention, so leave it plain. Bold the subheadings so they scan. Do not make the smallest text the faintest too.",
        "Scale type from a 16px base by 1.27, the square root of the golden ratio. Use 1.17, the cube root, for dense screens like dashboards and mobile. Straight 1.62 gets huge too fast.",
        "Fluid sizing: one line of CSS slides between the 320px size and the 1920px size, clamped with min and max. No breakpoints.",
        "Line height: about 150% for paragraphs, 110 to 130% for headings. Smaller text and longer lines want more. Auto falls apart at display sizes."
      ],
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "animejs.com",
      "domain": "animejs.com",
      "kind": "tool",
      "tags": [
        "motion",
        "animation"
      ],
      "url": "http://animejs.com/",
      "title": "Anime.js",
      "why": "A lightweight animation library. Worth knowing next to GSAP.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "recent.design",
      "domain": "recent.design",
      "kind": "gallery",
      "tags": [
        "web-design"
      ],
      "url": "https://recent.design/",
      "title": "Recent",
      "why": "Godly's new home, per Jack Roberts' five shelves. Best of recent design, daily.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "noiced.com",
      "domain": "noiced.com",
      "kind": "gallery",
      "tags": [
        "web-design"
      ],
      "url": "https://noiced.com/",
      "title": "Noiced",
      "why": "Daily web design inspiration. From Jack's shelf.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "landing.love",
      "domain": "landing.love",
      "kind": "gallery",
      "tags": [
        "motion",
        "landing-pages"
      ],
      "url": "https://landing.love/",
      "title": "Landing.love",
      "why": "2,000+ animation-heavy landing pages. Pairs with the pink notebook page.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "minimal.gallery",
      "domain": "minimal.gallery",
      "kind": "gallery",
      "tags": [
        "web-design",
        "minimal"
      ],
      "url": "https://minimal.gallery/",
      "title": "Minimal Gallery",
      "why": "Hand-picked minimal web design. For when the slab layout needs a diet.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "siteinspire.com",
      "domain": "siteinspire.com",
      "kind": "gallery",
      "tags": [
        "web-design"
      ],
      "url": "https://siteinspire.com/",
      "title": "Siteinspire",
      "why": "Old-school, still one of the cleanest galleries.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "app.notion.com/p/the-design-loop-free-guide-3b8e8d6bd13781ff8bf2fc06fd5d0aac",
      "domain": "app.notion.com",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "method"
      ],
      "url": "https://app.notion.com/p/The-Design-Loop-Free-Guide-3b8e8d6bd13781ff8bf2fc06fd5d0aac",
      "title": "The Design Loop",
      "why": "Interview, preflight, teardown, loop. Name a specific bar, write mechanisms not adjectives, then let three fresh critics judge the render until all three pass. Installed as /design-loop in this repo.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "app.notion.com/p/the-brand-asset-machine-3b3e8d6bd13781909d92c4d0cafc7c77",
      "domain": "app.notion.com",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "brand"
      ],
      "url": "https://app.notion.com/p/The-Brand-Asset-Machine-3b3e8d6bd13781909d92c4d0cafc7c77",
      "title": "The Brand Asset Machine",
      "why": "A skill that interviews you, fixes a palette, then generates a brand's logo, photography, one motion loop and a texture pack, all inside that palette. Three rules: one product build everywhere, no text in photos, approve the extras.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "app.notion.com/p/5-questions-to-answer-before-you-build-any-website-339e8d6bd1378133800bd681d1d24dfe",
      "domain": "app.notion.com",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "method"
      ],
      "url": "https://app.notion.com/p/5-Questions-to-Answer-Before-You-Build-Any-Website-339e8d6bd1378133800bd681d1d24dfe",
      "title": "5 Questions to Answer Before You Build Any Website",
      "why": "Who is the visitor, what is the one action, which objections need a section, what is the vibe in one word, and do brand assets exist yet. Answer these before the next HelioFlux or Heliopolis page.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "app.notion.com/p/claude-fable-5-website-design-prompts-3-levels-37ee8d6bd1378142b27be3a1480dd0d5",
      "domain": "app.notion.com",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "prompts"
      ],
      "url": "https://app.notion.com/p/Claude-Fable-5-Website-Design-Prompts-3-Levels-37ee8d6bd1378142b27be3a1480dd0d5",
      "title": "Website Design Prompts, 3 Levels",
      "why": "Level one describes a site in a line, level two recreates a reference, level three extracts a site's design DNA and rebuilds something original. Level three is the one that matches how this desk works.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "app.notion.com/p/the-ai-native-client-cms-free-build-blueprint-374e8d6bd13781559214ffd5ac6041f6",
      "domain": "app.notion.com",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "cms"
      ],
      "url": "https://app.notion.com/p/The-AI-Native-Client-CMS-Free-Build-Blueprint-374e8d6bd13781559214ffd5ac6041f6",
      "title": "The AI-Native Client CMS Build Blueprint",
      "why": "Ingest a site, freeze the design as a template, expose only content slots, and run every change through a deterministic validator so a client cannot break the layout. Filed for the day the lab needs an editor.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "easywebsitebuilder.tech",
      "domain": "easywebsitebuilder.tech",
      "kind": "tool",
      "tags": [
        "jack-roberts"
      ],
      "url": "https://easywebsitebuilder.tech/",
      "title": "Easy Website Builder",
      "why": "Jack's website builder. Saved to try, not yet opened.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "app.notion.com/p/gpt-6-astra-is-here-5-things-you-need-to-do-with-it-3d2e8d6bd137819f99b2f35862af517b",
      "domain": "app.notion.com",
      "kind": "reading",
      "tags": [
        "jack-roberts",
        "method"
      ],
      "url": "https://app.notion.com/p/GPT-6-Astra-Is-Here-5-Things-You-NEED-to-Do-With-It-3d2e8d6bd137819f99b2f35862af517b",
      "title": "Five real jobs for a new model",
      "why": "Five prompts with a way to check each: find the bottleneck, a one-screen business dashboard, build with the design loop then test like a first-time customer, a filmable UI system from one reference, and a money-leak audit with receipts.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "youtube:2ZwO6LhC0SU",
      "domain": "youtube.com",
      "kind": "video",
      "tags": [],
      "url": "https://www.youtube.com/watch?v=2ZwO6LhC0SU",
      "title": "Website design in three levels, with Jack Roberts",
      "author": "AI Automations with Jack",
      "added": "2026-09-24",
      "takeaways": [
        "Level one: describe the site in plain words and let the model one-shot it. Fast, and it looks like everyone else's.",
        "Level two: hand over a reference you love and ask for a recreation. Hard mode, and it copies more than it should.",
        "Level three: extract the reference's design DNA, typography, colour, spacing, layout, ratios, then rebuild something original from that blueprint. This is the one that matches the desk.",
        "Open on max effort for the first build, then drop to medium for everything after. Design judgment is where the effort dial matters.",
        "Awwwards is the place he finds references. Higgsfield or Kie.ai when the hero needs a video."
      ],
      "source": "manual"
    },
    {
      "id": "myheliopolis.com/meetings/2026-09-17",
      "domain": "myheliopolis.com",
      "kind": "site",
      "tags": [
        "mine",
        "heliopolis"
      ],
      "url": "https://myheliopolis.com/meetings/2026-09-17/#home",
      "title": "Heliopolis meeting room",
      "why": "The meeting page I built for 2026-09-17. Learned a ton making it. Kept here to measure the next one against.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "pretzel.thetravelprotocol.com",
      "domain": "pretzel.thetravelprotocol.com",
      "kind": "site",
      "tags": [
        "mine",
        "trip-atlas"
      ],
      "url": "https://pretzel.thetravelprotocol.com",
      "title": "Pretzel Protocol",
      "why": "The family trip atlas. Cream, navy, one attention colour, a delight budget of five. Mine, and still teaching me.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "ui.aceternity.com",
      "domain": "ui.aceternity.com",
      "kind": "tool",
      "tags": [
        "components",
        "motion"
      ],
      "url": "https://ui.aceternity.com",
      "title": "Aceternity UI",
      "why": "Animated heroes, spotlight cards, parallax grids. Jack's UI sniping arsenal: snipe it, then make it obey the system.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "reactbits.dev",
      "domain": "reactbits.dev",
      "kind": "tool",
      "tags": [
        "components",
        "motion"
      ],
      "url": "https://reactbits.dev",
      "title": "ReactBits",
      "why": "Unique animated micro-components nobody recognises from a template. Same rule: restyle to the tokens after sniping.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "relume.io",
      "domain": "relume.io",
      "kind": "tool",
      "tags": [
        "wireframes",
        "ai-design"
      ],
      "url": "https://www.relume.io",
      "title": "Relume",
      "why": "AI sitemaps and wireframes. Only useful after the five questions are answered, which is the whole point of Jack's guide.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "higgsfield.ai",
      "domain": "higgsfield.ai",
      "kind": "tool",
      "tags": [
        "ai-video",
        "brand-assets"
      ],
      "url": "https://higgsfield.ai",
      "title": "Higgsfield",
      "why": "AI image and video. The engine behind the Brand Asset Machine, and where the Magpie Collector already lives.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "kie.ai",
      "domain": "kie.ai",
      "kind": "tool",
      "tags": [
        "ai-video",
        "ai-images"
      ],
      "url": "https://kie.ai",
      "title": "Kie.ai",
      "why": "AI images and video by API. The other generator Jack plugs in for hero videos.",
      "added": "2026-09-24",
      "source": "manual"
    },
    {
      "id": "emilkowal.ski/skill",
      "title": "Emil Kowalski AI Skills for Design Engineers",
      "url": "https://emilkowal.ski/skill",
      "domain": "emilkowal.ski",
      "author": "Emil Kowalski",
      "kind": "tool",
      "tags": [
        "design-engineering",
        "animation",
        "motion",
        "ui-polish",
        "agent-skills",
        "react-native",
        "expo"
      ],
      "summary": "Emil Kowalski's AI Skills for Design Engineers is a collection of agent skills for improving UI craft, especially animation and design-engineering polish.",
      "takeaways": [
        "Useful for making AI-built interfaces feel less flat and generic after the first build exists.",
        "The broader skill set includes design-engineering guidance, animation creation, animation review, animation improvement audits, motion opportunity finding, prototyping variants, animation vocabulary, Apple-style motion principles, and UI library picking.",
        "Especially relevant to Kelly’s recurring concern that AI animation misses subtle continuity, timing, spacing, and physical-behavior details.",
        "Best use in the inspiration desk: an operating tool for motion polish, not just a reference gallery."
      ],
      "hasTranscript": false,
      "clippedAt": "2026-08-19T22:50:00-07:00",
      "source": "magpie+manual",
      "why": "Agent skills for motion polish: animation review, timing, spacing, and the physical details AI usually misses."
    },
    {
      "id": "savee.com",
      "title": "Savee",
      "url": "https://savee.com",
      "domain": "savee.com",
      "kind": "gallery",
      "tags": [
        "visual-inspiration",
        "references",
        "curation",
        "taste-library"
      ],
      "summary": "Savee is a curated visual inspiration platform for discovering, saving, and sharing design references.",
      "takeaways": [
        "Use Savee as a visual reference-discovery layer, especially when Pinterest/Dribbble feel too noisy or broad.",
        "Best use: collect references first, then name the shared vocabulary before asking AI to generate a page, image prompt, or build brief.",
        "Fits the Chase AI design workflow: curate taste, categorize references, describe the vocabulary, then use that library to prompt builds.",
        "Good categories to watch for Kelly projects: quiet premium layouts, editorial science, cinematic hero systems, typography treatment, gallery grids, and playful interface texture."
      ],
      "hasTranscript": false,
      "clippedAt": "2026-08-19T18:43:00-07:00",
      "source": "magpie+manual",
      "why": "A cleaner, more taste-driven reference feed for when Pinterest and Dribbble get noisy."
    },
    {
      "id": "youtube:7FU98O0JLHs",
      "title": "Turn Claude Into A Design GENIUS In 3 Simple Steps",
      "url": "https://www.youtube.com/watch?v=7FU98O0JLHs",
      "domain": "youtube.com",
      "author": "Chase AI",
      "kind": "video",
      "tags": [
        "ai-design",
        "web-design",
        "inspiration-library"
      ],
      "summary": "Chase AI lays out a practical anti-slop workflow for AI-assisted web design: build a curated inspiration library, use design-improvement tools and asset generators carefully, then create several…",
      "takeaways": [
        "Curate taste first: save screenshots and live URLs from Dribbble, Pinterest, Twitter/X, and actual websites instead of asking AI to design from an empty prompt.",
        "Turn the library into a simple web app that groups references by aesthetic/design type and explains the vocabulary behind each style.",
        "Each reference should expose keywords, an image prompt, and a copyable build brief so the design direction can be reused in future prompts.",
        "Use tools such as Impeccable/Taste-style critique skills, component inspiration libraries, and image/video generators as flexible support, not magic design replacement.",
        "For builds, cast a wide net first: generate several aesthetic directions, pick one, generate variants, then tweak visually with fonts, scale, accents, imagery, motion, and body layouts."
      ],
      "hasTranscript": true,
      "clippedAt": "2026-08-17T07:27:32.117469+00:00",
      "source": "magpie"
    },
    {
      "id": "happyhues.co",
      "title": "Happy Hues",
      "url": "https://www.happyhues.co/",
      "domain": "happyhues.co",
      "kind": "tool",
      "tags": [
        "design-inspiration",
        "color",
        "color-palette"
      ],
      "summary": "See color palette inspiration on a real example website.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:31.548Z",
      "source": "magpie+manual",
      "why": "Applied palettes: every color shown doing a job on a real page instead of floating in a swatch."
    },
    {
      "id": "fonts.google.com",
      "title": "Google Fonts",
      "url": "https://fonts.google.com/",
      "domain": "fonts.google.com",
      "kind": "tool",
      "tags": [
        "design-inspiration",
        "typography",
        "fonts"
      ],
      "summary": "Making the web more beautiful, fast, and open through great typography",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:29.576Z",
      "source": "magpie+manual",
      "why": "Implementable typography, with the loading and readability guidance to go with it."
    },
    {
      "id": "mobbin.com",
      "title": "Mobbin",
      "url": "https://mobbin.com/",
      "domain": "mobbin.com",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "ui-ux",
        "design-reference"
      ],
      "summary": "Save hours of UI & UX research with our library of 400,000+ fully searchable mobile & web app screenshots.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:27.416Z",
      "source": "magpie+manual",
      "why": "Real product screens and full user journeys. Mood first, then workflow evidence from here."
    },
    {
      "id": "behance.net/onboarding/hirercreative",
      "title": "Behance",
      "url": "https://www.behance.net/onboarding/hirerCreative",
      "domain": "behance.net",
      "author": "Behance",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "visual-inspiration"
      ],
      "summary": "Behance is the world's largest creative network for showcasing and discovering creative work",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:22.648Z",
      "source": "magpie+manual",
      "why": "Portfolio browsing and brand work. Lighter use than Dribbble, better for whole identities."
    },
    {
      "id": "dribbble.com",
      "title": "Dribbble",
      "url": "https://dribbble.com/",
      "domain": "dribbble.com",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "visual-inspiration"
      ],
      "summary": "Find Top Designers & Creative Professionals on Dribbble. We are where designers gain inspiration, feedback, community, and jobs. Your best resource to discover and connect with designers worldwide.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:19.862Z",
      "source": "magpie+manual",
      "why": "Quick visual and branding sampling. Search web design, sort by popular, screenshot what stops you."
    },
    {
      "id": "pinterest.com",
      "title": "Pinterest",
      "url": "https://www.pinterest.com/",
      "domain": "pinterest.com",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "visual-inspiration"
      ],
      "summary": "Discover recipes, home ideas, style inspiration and other ideas to try.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:17.607Z",
      "source": "magpie+manual",
      "why": "The broadest, least precise end of the taste workflow. Mood boards, then promote the pins that actually shape something."
    },
    {
      "id": "pageflows.com",
      "title": "Page Flows",
      "url": "https://pageflows.com/",
      "domain": "pageflows.com",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "ui-ux",
        "design-reference"
      ],
      "summary": "Explore 100,000+ recorded user flows, app screens, and UI patterns from Airbnb, Uber, Netflix & more. Save hours on UX research with Page Flows.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:13.919Z",
      "source": "magpie+manual",
      "why": "The sequence layer: how a journey unfolds across screens, not just how one screen looks."
    },
    {
      "id": "refero.design",
      "title": "Refero",
      "url": "https://refero.design/",
      "domain": "refero.design",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "web-design",
        "website-examples",
        "ui-ux",
        "design-reference"
      ],
      "summary": "The largest collection of UI/UX references and design inspiration for web and iOS. Explore tens of thousands of screenshots with advanced search capabilities",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:11.584Z",
      "source": "magpie+manual",
      "why": "Task-specific web and iOS patterns from real products. My go-to for how a login, a filter, or an onboarding step actually looks."
    },
    {
      "id": "lapa.ninja",
      "title": "Lapa Ninja",
      "url": "https://www.lapa.ninja/",
      "domain": "lapa.ninja",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "web-design",
        "website-examples"
      ],
      "summary": "Browse 7,300+ landing page designs from portfolios, agencies & startups. Find high-converting examples with screenshots & videos. SaaS, e-commerce & more.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:09.071Z",
      "source": "magpie+manual",
      "why": "Full-page landing benchmarks. Scroll the whole thing and count the sections."
    },
    {
      "id": "onepagelove.com",
      "title": "One Page Love",
      "url": "https://onepagelove.com",
      "domain": "onepagelove.com",
      "author": "Rob Hope, @robhope",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "web-design",
        "website-examples"
      ],
      "summary": "One Page Love is a One Page website design gallery showcasing the best Single Page websites, templates and resources.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:06.193Z",
      "source": "magpie+manual",
      "why": "Tighter single-page sites and section references. Good for section sequencing."
    },
    {
      "id": "21st.dev",
      "title": "21st.dev",
      "url": "https://21st.dev",
      "domain": "21st.dev",
      "kind": "tool",
      "tags": [
        "design-inspiration",
        "ui-ux",
        "design-reference"
      ],
      "summary": "Community registry of 10,000+ hand-crafted React and Tailwind CSS components and templates. Preview live, install with one command, for you and your AI agent.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:04.484Z",
      "source": "magpie+manual"
    },
    {
      "id": "awwwards.com",
      "title": "Awwwards",
      "url": "https://www.awwwards.com/",
      "domain": "awwwards.com",
      "kind": "gallery",
      "tags": [
        "design-inspiration",
        "web-design",
        "website-examples"
      ],
      "summary": "Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:29:00.818Z",
      "source": "magpie+manual",
      "why": "Best for high-polish website benchmarks. Start here when a build begins from style uncertainty."
    },
    {
      "id": "stitch.withgoogle.com",
      "title": "Stitch",
      "url": "https://stitch.withgoogle.com",
      "domain": "stitch.withgoogle.com",
      "kind": "tool",
      "tags": [
        "design-inspiration",
        "design-tool",
        "ai-design",
        "ui-ux"
      ],
      "summary": "Stitch generates UIs for mobile and web applications, making design ideation fast and easy.",
      "hasTranscript": false,
      "clippedAt": "2026-07-25T12:28:12.197Z",
      "source": "magpie+manual",
      "why": "Google's AI UI ideation tool. Treat the output as a sketch, not a spec."
    },
    {
      "id": "github.com/leonxlnx/taste-skill",
      "title": "Taste Skill",
      "url": "https://github.com/Leonxlnx/taste-skill",
      "domain": "github.com",
      "kind": "repo",
      "tags": [
        "skills",
        "design-tools",
        "frontend"
      ],
      "summary": "Portable frontend/design agent skills aimed at reducing generic AI UI output.",
      "hasTranscript": false,
      "clippedAt": "2026-07-04T16:15:17.745728+00:00",
      "source": "magpie"
    },
    {
      "id": "github.com/goabstract/awesome-design-tools",
      "title": "Awesome Design Tools",
      "url": "https://github.com/goabstract/Awesome-Design-Tools",
      "domain": "github.com",
      "kind": "repo",
      "tags": [
        "design-tools",
        "brand",
        "frontend",
        "creative-tooling"
      ],
      "summary": "Large curated list of design tools covering accessibility, animation, design systems, design-to-code, icons, illustrations, mockups, prototyping, social graphics, stock media, UI design, user…",
      "hasTranscript": false,
      "clippedAt": "2026-07-04T16:11:11.683203+00:00",
      "source": "magpie"
    },
    {
      "id": "principles.design",
      "title": "Principles.design",
      "url": "https://principles.design/",
      "domain": "principles.design",
      "kind": "gallery",
      "tags": [
        "inspiration",
        "web-design"
      ],
      "hasTranscript": false,
      "clippedAt": "2026-07-02T23:30:22.579000+00:00",
      "source": "magpie+manual",
      "why": "An open collection of design principles from real teams. Steal the wording, keep the discipline."
    },
    {
      "id": "motionsites.ai",
      "title": "Motion Sites",
      "url": "https://motionsites.ai/",
      "domain": "motionsites.ai",
      "kind": "gallery",
      "tags": [
        "inspiration",
        "web-design"
      ],
      "hasTranscript": false,
      "clippedAt": "2026-07-02T23:16:52.175000+00:00",
      "source": "magpie+manual",
      "why": "A gallery of motion-first websites. Watch how each one moves before reading a word."
    },
    {
      "id": "ciechanow.ski/mechanical-watch",
      "title": "Bartosz Ciechanowski",
      "url": "https://ciechanow.ski/mechanical-watch/",
      "domain": "ciechanow.ski",
      "kind": "site",
      "tags": [
        "educational",
        "interactive"
      ],
      "hasTranscript": false,
      "clippedAt": "2026-02-24T00:00:00Z",
      "source": "magpie+manual",
      "why": "Interactive explainers where the page itself does the teaching. The gold standard for learning by playing."
    },
    {
      "id": "bruno-simon.com",
      "title": "Bruno Simon",
      "url": "https://bruno-simon.com/",
      "domain": "bruno-simon.com",
      "kind": "site",
      "tags": [
        "portfolio",
        "3d",
        "interactive"
      ],
      "hasTranscript": false,
      "clippedAt": "2026-02-24T00:00:00Z",
      "source": "magpie+manual",
      "why": "A portfolio you drive a car through. Proof that a site can be a toy and still land the job."
    },
    {
      "id": "codingfont.com",
      "title": "Coding Font",
      "url": "https://codingfont.com",
      "domain": "codingfont.com",
      "kind": "tool",
      "tags": [
        "tools",
        "dev",
        "fonts"
      ],
      "hasTranscript": false,
      "clippedAt": "2026-02-24T00:00:00Z",
      "source": "magpie+manual",
      "why": "A tournament bracket for monospace fonts. Ridiculous and effective."
    },
    {
      "id": "skins.webamp.org/index.html",
      "title": "Webamp skins",
      "url": "https://skins.webamp.org/index.html",
      "domain": "skins.webamp.org",
      "kind": "site",
      "tags": [
        "nostalgia",
        "music"
      ],
      "hasTranscript": false,
      "clippedAt": "2026-02-24T00:00:00Z",
      "source": "magpie+manual",
      "why": "A museum of Winamp skins. Nostalgia as a lesson in personality over polish."
    },
    {
      "id": "igloo.inc",
      "title": "Igloo Inc",
      "url": "https://igloo.inc",
      "domain": "igloo.inc",
      "kind": "site",
      "tags": [
        "cool"
      ],
      "hasTranscript": false,
      "clippedAt": "2026-02-24T00:00:00Z",
      "source": "magpie+manual",
      "why": "Scroll-driven 3D storytelling. Study how the motion carries the narrative."
    },
    {
      "id": "fontsinuse.com",
      "title": "Fonts In Use",
      "url": "https://fontsinuse.com/",
      "domain": "fontsinuse.com",
      "kind": "tool",
      "tags": [
        "fonts",
        "typography",
        "reference",
        "tools"
      ],
      "hasTranscript": false,
      "clippedAt": "2026-02-24T00:00:00Z",
      "source": "magpie+manual",
      "why": "Typography in the wild, indexed by typeface and industry. Proof of what a font feels like in context."
    }
  ]
};
